# Generated by Django 3.0.1 on 2020-07-03 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=2000)),
                ('Option1', models.CharField(max_length=2000)),
                ('Option2', models.CharField(max_length=2000)),
                ('Option3', models.CharField(max_length=2000)),
                ('Points3', models.IntegerField(default=0, null=True)),
                ('Points2', models.IntegerField(default=0, null=True)),
                ('Points1', models.IntegerField(default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
